### ISSUE TITLE
Revival checklist

### ISSUE THREAD

**Issue by hmaarrfk** [ukoethe/vigra#515]
9. [x] https://github.com/ukoethe/vigra/pull/509
1. [x] Ensure the CIs are working again on with semi-modern versions of compilers + python
      * [x] linux - https://github.com/ukoethe/vigra/pull/514
      * [x] OSX - https://github.com/ukoethe/vigra/pull/523 -- opened https://github.com/ukoethe/vigra/issues/535
      * [x] Windows - https://github.com/ukoethe/vigra/pull/526
3. [x] Fix matlab compilation: https://github.com/ukoethe/vigra/pull/513
2. [x] Update changelog with recent PRs - https://github.com/ukoethe/vigra/pull/540
4. [x] Release new version
8. [x] https://github.com/ukoethe/vigra/pull/511
6. [x] nose->pytest https://github.com/ukoethe/vigra/issues/508
7. [x] deprecated functions https://github.com/ukoethe/vigra/issues/505
10. [x] https://github.com/ukoethe/vigra/pull/510
11. [x] address https://github.com/ukoethe/vigra/issues/482
5. [x] Address simple warnings in the compilation
6. [x] Python 3.12 support? https://github.com/conda-forge/vigra-feedstock/pull/120#event-10517055426
12. [x] Release new version
13. [x] Rebuild vigra-numpy support https://github.com/conda-forge/vigra-feedstock/issues/134
    * [x] numpy2 support
    * [x] General new compiler support (Windows and OSX are breaking today).

**Comment by hmaarrfk** [comment]
I've pinned this issue for prominence.

Essentially, a lot can get unclogged if anybody is willing to help getting the OSX CI working again.

**Comment by hmaarrfk** [comment]
@k-dominik given that the CIs are back and running, I think we are good releasing a "quick version" without any other changes before moving on to changes to the code base. 

This release mostly includes changes to the build architecture to bring it in-line with more modern tooling.

The follow-on PRs address compatibility with new standards of C++ when we can create a new version bump delineating the different changes for downstream.

**Comment by k-dominik** [comment]
Oh yes please, can't believe I finally can stop bumping build numbers manually for vigra when used as a dependency! Awesome that you put in the effort to make it work!

**Comment by hmaarrfk** [comment]
New release just cut. 

https://github.com/ukoethe/vigra/releases/tag/Version-1-11-2

**Comment by hmaarrfk** [comment]
I opened up a specific numpy2 issue.

**Comment by hmaarrfk** [comment]
alright. 2 year slog. thanks everybody for helping!

**Comment by hmaarrfk** [comment]
There is likely more to do, that is the windows build don't pass the tests, but we can start to attack these issues one at a time!!!

Super excited for this.

**Comment by k-dominik** [comment]
Hey @hmaarrfk,

thank you for putting in so much effort in keeping vigra running!
